name: quantecon
channels:
  - default
dependencies:
  - python=3.11
  - anaconda=2024.02
  - pip
  - pip:
    - jupyter-book==0.15.1
    - quantecon-book-theme==0.7.1
    - sphinx-tojupyter==0.3.0
    - sphinxext-rediraffe==0.2.7
    - sphinx-reredirects==0.1.3
    - sphinx-exercise==0.4.1
    - ghp-import==1.1.0
    - sphinxcontrib-youtube==1.1.0
    - sphinx-togglebutton==0.3.1
    - array-to-latex
    - prettytable
    - kaleido
    - arviz
    # Docker Requirements
    - pytz
    # Docutils Issue (https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/322)
    - docutils==0.17.1

