name: lecture-jax
channels:
  - default
dependencies:
  - python=3.11
  - anaconda=2023.09
  - pip
  - pip:
    - jupyter-book==0.15.1
    - docutils==0.17.1
    - quantecon-book-theme==0.7.1
    - sphinx-tojupyter==0.3.0
    - sphinxext-rediraffe==0.2.7
    - sphinx-exercise==0.4.1
    - ghp-import==1.1.0
    - sphinxcontrib-youtube==1.1.0
    - sphinx-togglebutton==0.3.1
    - arviz==0.13.0
    - kaleido
    # Sandpit Requirements
    # - quantecon
    # - array-to-latex
    # - PuLP
    # - cvxpy
    # - cvxopt
    # - cylp
    # - prettytable
